include $(THEOS)/makefiles/common.mk

FRAMEWORK_NAME = MMLanScan

MMLanScan_FILES = $(wildcard *.m)
MMLanScan_PUBLIC_HEADERS = $(wildcard *.h)
MMLanScan_INSTALL_PATH = /Library/Frameworks
MMLanScan_CFLAGS = -fobjc-arc

include $(THEOS_MAKE_PATH)/framework.mk
